# Generated by Django 3.0.8 on 2020-07-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Blog Created At:')),
                ('updated_at', models.DateTimeField(verbose_name='Blog Updated At:')),
                ('blog', models.CharField(max_length=5000)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
