# Generated by Django 3.0.8 on 2020-07-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog',
            field=models.TextField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Blog Created At:'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Blog Updated At:'),
        ),
    ]
