# Generated by Django 3.0.8 on 2020-07-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_page', '0003_blogs_user_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='user_file',
        ),
    ]
